# Generated by Django 4.1.2 on 2023-03-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='salary',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
